Update cl-dot.lisp
michaelw/cl-dot pull request #41
Opened 2024-01-09 00:47 UTC by ko56

Edit of function dot-graph to (automatically) compute an output format based on the suffix of the output file.

2024-01-09 18:57 UTC, rpgoldman commented
At the same time we do this, should we change the default type to PDF?  Postscript is pretty much dead now, in favor of PDF.

2024-01-09 22:33 UTC, rpgoldman commented on cl-dot.lisp
>    (when (null format) (setf format :ps))
This line is unnecessary.  Unless the caller explicitly writes `(dot-graph foo "/my/out/file.xxx" :format nil)`, any failure to specify a format will get the default value.

2024-01-09 22:34 UTC, rpgoldman requested changes
This looks great -- we just might as well fix a couple of other things at the same time.

2024-01-09 22:34 UTC, rpgoldman commented on cl-dot.lisp
>  (defun dot-graph (graph outfile &key (format :ps) (directed t))
Suggest we modify to `(format :pdf)` -- hardly anyone uses postscript any more.

2024-01-09 22:35 UTC, rpgoldman commented on cl-dot.lisp
>          (format (format nil "-T~(~a~)" format))
Minor nit -- aren't these lines incorrectly indented?

2024-01-24 19:28 UTC, rpgoldman commented on cl-dot.lisp
>          (format (format nil "-T~(~a~)" format))
Also suggest replace without destructive modification of parameter variable.

2024-01-24 19:30 UTC, rpgoldman commented
@ko56 Please review my mods.

2024-01-25 14:08 UTC, ko56 reviewed
Reviewed. I also suggested a fix for not modifying the `outfile` parameter. I hope you can see it somewhere. Github is confusing me.

2024-01-25 20:58 UTC, rpgoldman commented
I think we are good to go. The only thing that bothers me a little is that I don't have a test for this, and it's not a function that I ever use myself: I always just print the DOT graph and then invoke `dot` from the command line to create a graphical output file.

@ko56 Would you mind pulling an update to your branch, and then running it to make sure it works for you as expected?  If it does, I will merge.

2024-01-26 23:06 UTC, ko56 commented
OK, it works for me.

2024-02-15 15:42 UTC, merged